# Generated by Django 5.0.4 on 2024-04-22 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_newsletter_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ('status',), 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='status_newsletter',
            new_name='status',
        ),
    ]
