# Generated by Django 5.0.4 on 2024-04-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_newsletter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='client',
            field=models.ManyToManyField(related_name='newsletter', to='client.serviceclient'),
        ),
    ]
