# Generated by Django 5.0.4 on 2024-04-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_message_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='client',
            field=models.ManyToManyField(related_name='newsletter', to='client.serviceclient', verbose_name='Клиент'),
        ),
    ]
