# Generated by Django 5.0.4 on 2024-04-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_newsletter_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ('status',), 'permissions': [('set_is_activated', 'Может отключать рассылку')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AddField(
            model_name='newsletter',
            name='is_activated',
            field=models.BooleanField(default=True, verbose_name='Активная'),
        ),
    ]
